// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1733817093);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1733817089);
user_pref("calendar.list.sortOrder", "91741e6a-4a78-4197-be9c-8d673be86798");
user_pref("calendar.registry.91741e6a-4a78-4197-be9c-8d673be86798.calendar-main-default", true);
user_pref("calendar.registry.91741e6a-4a78-4197-be9c-8d673be86798.calendar-main-in-composite", true);
user_pref("calendar.registry.91741e6a-4a78-4197-be9c-8d673be86798.disabled", true);
user_pref("calendar.registry.91741e6a-4a78-4197-be9c-8d673be86798.name", "Home");
user_pref("calendar.registry.91741e6a-4a78-4197-be9c-8d673be86798.type", "storage");
user_pref("calendar.registry.91741e6a-4a78-4197-be9c-8d673be86798.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1733817097916");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1733817085);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241009170210");
user_pref("extensions.lastAppVersion", "115.16.0");
user_pref("extensions.lastPlatformVersion", "115.16.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"f25a3e21-e844-4c69-9f66-992a1f9c037a\",\"google@search.mozilla.org\":\"9e539c8a-2ce2-445a-95cd-3eb1ba6c5b4c\",\"ddg@search.mozilla.org\":\"49bd5513-eb23-412d-948f-32ee83d74fdf\",\"amazondotcom@search.mozilla.org\":\"26ef1b0f-9ea3-4ad9-93c8-12054344759a\",\"wikipedia@search.mozilla.org\":\"b4939e58-2686-4322-8798-0ce2807ff833\",\"bing@search.mozilla.org\":\"cecc5c31-d375-41ef-97af-ee0b43e7c274\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "346c95db-d132-4a6e-81a6-37bc89c2180");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.16.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1733817071);
user_pref("toolkit.telemetry.cachedClientID", "79d4b1bb-09e3-4a13-aeb3-a01d63da2ef2");
user_pref("toolkit.telemetry.previousBuildID", "20241009170210");
